// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: 'extraction_unavailable' | 'internal_server_error' | 'note_not_found' | 'source_text_not_actionable';
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: 'ok';
};

/**
 * NoteCategory
 */
export type NoteCategory = 'mechanical' | 'electrical' | 'software' | 'safety' | 'other';

/**
 * NoteListResponse
 */
export type NoteListResponse = {
    /**
     * Items
     */
    items: Array<NoteResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * NotePriority
 */
export type NotePriority = 'low' | 'medium' | 'high' | 'critical';

/**
 * NoteResponse
 */
export type NoteResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Source Text
     */
    source_text: string;
    /**
     * Title
     */
    title: string;
    category: NoteCategory;
    priority: NotePriority;
    status: NoteStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Resolved At
     */
    resolved_at: string | null;
};

/**
 * NoteSortField
 */
export type NoteSortField = 'priority' | 'created_at';

/**
 * NoteStatus
 */
export type NoteStatus = 'open' | 'resolved';

/**
 * RequestValidationErrorResponse
 */
export type RequestValidationErrorResponse = {
    /**
     * Detail
     */
    detail: Array<ValidationErrorDetail>;
};

/**
 * SetNoteStatusRequest
 */
export type SetNoteStatusRequest = {
    status: NoteStatus;
};

/**
 * SortDirection
 */
export type SortDirection = 'asc' | 'desc';

/**
 * SubmitNoteRequest
 */
export type SubmitNoteRequest = {
    /**
     * Source Text
     */
    source_text: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ValidationErrorDetail
 */
export type ValidationErrorDetail = {
    /**
     * Loc
     */
    loc: Array<string | number>;
    /**
     * Msg
     */
    msg: string;
    /**
     * Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown | null;
    /**
     * Ctx
     */
    ctx?: {
        [key: string]: unknown;
    } | null;
};

export type GetHealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthHealthGetErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetHealthHealthGetError = GetHealthHealthGetErrors[keyof GetHealthHealthGetErrors];

export type GetHealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetHealthHealthGetResponse = GetHealthHealthGetResponses[keyof GetHealthHealthGetResponses];

export type GetNotesNotesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         */
        category?: NoteCategory | null;
        /**
         * Priority
         */
        priority?: NotePriority | null;
        /**
         * Status
         */
        status?: NoteStatus | null;
        sort_by?: NoteSortField;
        direction?: SortDirection;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/notes';
};

export type GetNotesNotesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetNotesNotesGetError = GetNotesNotesGetErrors[keyof GetNotesNotesGetErrors];

export type GetNotesNotesGetResponses = {
    /**
     * Successful Response
     */
    200: NoteListResponse;
};

export type GetNotesNotesGetResponse = GetNotesNotesGetResponses[keyof GetNotesNotesGetResponses];

export type PostNoteNotesPostData = {
    body: SubmitNoteRequest;
    path?: never;
    query?: never;
    url: '/notes';
};

export type PostNoteNotesPostErrors = {
    /**
     * Response 422 Post Note Notes Post
     *
     * Unprocessable Entity
     */
    422: ErrorResponse | RequestValidationErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type PostNoteNotesPostError = PostNoteNotesPostErrors[keyof PostNoteNotesPostErrors];

export type PostNoteNotesPostResponses = {
    /**
     * Successful Response
     */
    201: NoteResponse;
};

export type PostNoteNotesPostResponse = PostNoteNotesPostResponses[keyof PostNoteNotesPostResponses];

export type PatchNoteNotesNoteIdPatchData = {
    body: SetNoteStatusRequest;
    path: {
        /**
         * Note Id
         */
        note_id: string;
    };
    query?: never;
    url: '/notes/{note_id}';
};

export type PatchNoteNotesNoteIdPatchErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PatchNoteNotesNoteIdPatchError = PatchNoteNotesNoteIdPatchErrors[keyof PatchNoteNotesNoteIdPatchErrors];

export type PatchNoteNotesNoteIdPatchResponses = {
    /**
     * Successful Response
     */
    200: NoteResponse;
};

export type PatchNoteNotesNoteIdPatchResponse = PatchNoteNotesNoteIdPatchResponses[keyof PatchNoteNotesNoteIdPatchResponses];
