// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
    detail: z.enum([
        'extraction_unavailable',
        'internal_server_error',
        'note_not_found',
        'source_text_not_actionable'
    ])
});

/**
 * HealthResponse
 */
export const zHealthResponse = z.object({
    status: z.literal('ok')
});

/**
 * NoteCategory
 */
export const zNoteCategory = z.enum([
    'mechanical',
    'electrical',
    'software',
    'safety',
    'other'
]);

/**
 * NotePriority
 */
export const zNotePriority = z.enum([
    'low',
    'medium',
    'high',
    'critical'
]);

/**
 * NoteSortField
 */
export const zNoteSortField = z.enum(['priority', 'created_at']);

/**
 * NoteStatus
 */
export const zNoteStatus = z.enum(['open', 'resolved']);

/**
 * NoteResponse
 */
export const zNoteResponse = z.object({
    id: z.uuid(),
    source_text: z.string(),
    title: z.string(),
    category: zNoteCategory,
    priority: zNotePriority,
    status: zNoteStatus,
    created_at: z.iso.datetime({ offset: true }),
    resolved_at: z.iso.datetime({ offset: true }).nullable()
});

/**
 * NoteListResponse
 */
export const zNoteListResponse = z.object({
    items: z.array(zNoteResponse),
    total: z.int()
});

/**
 * SetNoteStatusRequest
 */
export const zSetNoteStatusRequest = z.object({
    status: zNoteStatus
});

/**
 * SortDirection
 */
export const zSortDirection = z.enum(['asc', 'desc']);

/**
 * SubmitNoteRequest
 */
export const zSubmitNoteRequest = z.object({
    source_text: z.string().min(1).max(2000)
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * ValidationErrorDetail
 */
export const zValidationErrorDetail = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().nullish(),
    ctx: z.record(z.string(), z.unknown()).nullish()
});

/**
 * RequestValidationErrorResponse
 */
export const zRequestValidationErrorResponse = z.object({
    detail: z.array(zValidationErrorDetail)
});

/**
 * Successful Response
 */
export const zGetHealthHealthGetResponse = zHealthResponse;

export const zGetNotesNotesGetQuery = z.object({
    category: zNoteCategory.nullish(),
    priority: zNotePriority.nullish(),
    status: zNoteStatus.nullish(),
    sort_by: zNoteSortField.optional().default('priority'),
    direction: zSortDirection.optional().default('desc'),
    limit: z.int().gte(1).lte(100).optional().default(50),
    offset: z.int().gte(0).optional().default(0)
});

/**
 * Successful Response
 */
export const zGetNotesNotesGetResponse = zNoteListResponse;

export const zPostNoteNotesPostBody = zSubmitNoteRequest;

/**
 * Successful Response
 */
export const zPostNoteNotesPostResponse = zNoteResponse;

export const zPatchNoteNotesNoteIdPatchBody = zSetNoteStatusRequest;

export const zPatchNoteNotesNoteIdPatchPath = z.object({
    note_id: z.uuid()
});

/**
 * Successful Response
 */
export const zPatchNoteNotesNoteIdPatchResponse = zNoteResponse;
